@startuml
    actor AdminUser
    entity router
    entity UserControler
    entity Twig
    entity Doctrine

    AdminUser -> router : I want create user
    router -> UserControler : createAction()
    UserControler -> Twig : generate html page \nfor user creation
    Twig -> AdminUser : html page
    AdminUser -> router : Informations for user creation
    router -> UserControler : createAction()
    UserControler -> Doctrine : insert these data in database
    Doctrine -> UserControler : Done
    UserControler -> Twig : Generate the html page
    Twig -> AdminUser : Html page
@enduml