@startuml
    actor LoggedUser
    entity router
    entity TaskControler
    entity Twig
    entity Doctrine

    LoggedUser -> router : I want create task
    router -> TaskControler : createAction()
    TaskControler -> Twig : Generate the creation \n task's page
    Twig -> LoggedUser : The creation \n task's page
    LoggedUser -> router : My data for create task
    router -> TaskControler : createAction()
    TaskControler -> Doctrine : Put this data in the database
    Doctrine -> TaskControler : Done
    TaskControler -> Twig : Generate the html page
    Twig -> LoggedUser : Html page
@enduml