@startuml
    actor AdminUser
    entity router
    entity UserControler
    entity Twig
    entity Doctrine

    AdminUser -> router : I want a list of user
    router -> UserControler : listAction()
    UserControler -> Doctrine : give me the list of the user
    Doctrine -> UserControler : Done
    UserControler -> Twig : Generate the html page
    Twig -> AdminUser : Html page
@enduml